export enum Permission {
  // Invoice permissions
  INVOICE_CREATE = 'INVOICE_CREATE',
  INVOICE_READ = 'INVOICE_READ',
  INVOICE_UPDATE = 'INVOICE_UPDATE',
  INVOICE_DELETE = 'INVOICE_DELETE',

  // Shift and machine logs
  SHIFT_LOG = 'SHIFT_LOG',
  SHIFT_LOG_READ = 'SHIFT_LOG_READ',
  MACHINE_MANAGE = 'MACHINE_MANAGE',

  // Karigar and uchapat advances
  KARIGAR_MANAGE = 'KARIGAR_MANAGE',
  UCHAPAT_MANAGE = 'UCHAPAT_MANAGE',
  UCHAPAT_READ = 'UCHAPAT_READ',

  // Challans
  CHALLAN_CREATE = 'CHALLAN_CREATE',
  CHALLAN_READ = 'CHALLAN_READ',
  CHALLAN_UPDATE = 'CHALLAN_UPDATE',

  // Accounting & Tally
  TALLY_EXPORT = 'TALLY_EXPORT',
  MUNIM_ACCESS = 'MUNIM_ACCESS',
  DAYBOOK_VIEW = 'DAYBOOK_VIEW',
  HISAB_GENERATE = 'HISAB_GENERATE',

  // Company and settings
  COMPANY_SETTINGS_MANAGE = 'COMPANY_SETTINGS_MANAGE',
  AUDIT_LOG_VIEW = 'AUDIT_LOG_VIEW',
}
